# Distribuição Weibull

A função densidade de probabilidade associada a variável aleatória tempo até o evento $t$, possui uma grande variedade de formas, sendo sua função densidade, possuindo uma propriedade básica: a função taxa de falha sendo monótona, ou seja, crescente, decrescente ou constante.

Com distribuição Weibull é dada por:

$$
f(t) = \frac{\gamma}{\alpha^{\gamma}}\cdot t^{(\gamma-1)} \cdot exp\left[-\left(\frac{t}{\alpha}\right)^{\gamma} \right], \ t>0 
$$

E função de sobrevivência dada por:\
$$
S(t) = exp\left[ - \left(\frac{t_{i}}{\alpha}\right)^{\gamma}\right]
$$

Os parâmetros de escala e forma, $\alpha$ e $\gamma$ são positivos. O parâmetro $\alpha$ tem mesma medida de unidade de $t$ e $\gamma$ não tendo unidade de medida.

## Função de verossimilhança é dada por:

$$
L(\theta | t) = \prod_{i=1}^{n} \left[ \left( \frac{\gamma}{\alpha^{\gamma}} \cdot t_{i}^{\gamma-1} \cdot \exp\left[ -\left( \frac{t_{i}}{\alpha} \right)^{\gamma} \right] \right)^{\delta_{i}} \cdot \left( \exp\left[ -\left( \frac{t_{i}}{\alpha} \right)^{\gamma} \right] \right)^{1-\delta_{i}} \right]
$$


## Log-verossimilhança da Weibull:

$$
\ell[L(\theta | t)] = \sum_{i=1}^{n} \left[ \delta_{i} \log \left( \frac{\gamma}{\alpha^{\gamma}} \cdot t_{i}^{\gamma-1} \right) - \left( \frac{t_{i}}{\alpha} \right)^{\gamma} \right]
$$

$$
\ell[L(\theta | t)] = \sum_{i=1}^{n} \left[ \delta_{i} \left[ \log(\gamma) - \gamma \log(\alpha) + (\gamma - 1) \log(t_{i}) \right] - \left( \frac{t_{i}}{\alpha} \right)^{\gamma} \right]
$$

## Distribuição Log-Weibull (Gumbel)

$$L(\theta | y) = \prod_{i=1}^n \left[ \left( \frac{1}{\sigma} \exp \left[ \frac{y_i - \mu}{\sigma} - \exp \left( \frac{y_i - \mu}{\sigma} \right) \right] \right)^{\delta_i} \cdot \left( \exp \left[ -\exp \left( \frac{y_i - \mu}{\sigma} \right) \right] \right)^{1-\delta_i} \right]$$

$$\ell[L(\theta|y)] = \sum_{i=0}^{n}\left[\delta_{i} \log\left(\frac{1}{\sigma} \exp \left[ \frac{y_i - \mu}{\sigma} - \exp \left( \frac{y_i - \mu}{\sigma} \right) \right] \right) + (1-\delta_i) \log \left( \exp \left[ -\exp \left( \frac{y_i - \mu}{\sigma} \right) \right] \right)\right]$$

Desenvolvendo as exponencias, aplicando os logs e separando os termos multiplicados na segunda parte da equação por $1-\delta_{i}$.

$$-\delta_{i} \exp \left[ \frac{y_i - \mu}{\sigma} \right] - \exp \left[\frac{y_{i} - \mu}{\sigma} \right]+ \delta{i} \exp \left[\frac{y_{i} - \mu}{\sigma} \right]$$

$$\ell[L(\theta | y)] = \sum_{i=1}^n \left[ \delta_i \left[ -\log(\sigma) + \left( \frac{y_i - \mu}{\sigma} \right) \right] - \exp \left( \frac{y_i - \mu}{\sigma} \right) \right]$$









































