---
format:
  html:
    embed-resources: true
---

# Censura intervalar e dados grupados

## Censuras

### Censuras à direita

São caracterizadas por situações em que o evento de interesse não ocorreu até a última visita e, sendo assim, se assume que $T$ pertence ao intervalo (L, $\infty$), com $L$ o tempo decorrido desde o início do estudo até a última visita e $U = \infty$.

### Censuras à esquerda

São caracterizadas por aquelas situações em que o evento de interesse ocorreu anterior à primeira visita.
Nesses casos, se assume que $T$ ocorreu no intervalo (0,U\], com L= 0 representando o inicío do estudo e $U$ o tempo decorrido desde o início do estudo até a primeir a visita.

### Evento exato

Chamado também de tempo exato de falha, se tem o evento de interesse que ocorreu exatamente no momento de uma das visita (no caso clínico, agropecuário etc.), onde se considera que T = L = U.

Em resumo, esses são casos particulares de dados de sobrevivência intervalar, em que dados de sobrevivência intervalar generalizam qualquer situação em que pode ocorrer combinações de tempos de falh (exatos ou intervalares) e censuras à direita e à esquerda.

### Dados grupados

Ocorre quando todas as unidades amostrais são monitoradas nos mesmos instantes, existindo periodicidade.
No entanto, uma parte das unidades amostrais pode ter sido monitorada em outro intervalo e outra também em outro intervalo, exemplo: acada cinco dias, e outro a cada sete dias.
Nesse caso, temos dados de censura intervalar e não grupados.

Dados grupados são frequentemente associados às situações com excesso de empates.
Se destaca que o termo "empate" tem sentido apenas para dados grupados, em que todas unidades amostrais são monitoradas exatamente nos mesmos tempos.

## Estimador não paramétrico de Turnbull

Proposto por Turnbull (1976) para estimar função de sobrevivência em contexto intervalar, o estimador não possui forma analítica fechada, se baseando em procedimento iterativo e consistindo em modificar o estimador de Kaplan-Meier.

Em situações que o tempo exato é desconhecido, mas se sabe que $T_{i} \in (L_{i},U_{i}]$ ou uma sequência de tempos que inclui todos os limites $L_{i} \; e \; U_{i}$ ou $T_{i} \in (L_{i}, \infty), i = 1,..,n,$ considerando 0 = $\tau_{0} < ... < \tau_{m}$ uma sequência de tempos que inclui todos os limites $L_{i} \; e \; U_{i}$.

Para i-éssima observação, i = 1,...,n, se define um peso $\alpha_{ij}$ o qual assume valor 1, se o intervalo ($\tau_{j-1},\tau{j}$\] está contido no intervalo $(L_{i},U_{i}]$, e valor zero, caso contrário, onde $\alpha_{ij}$ indica se o evento que ocorreu no intervalo $(L_{i},U_{i}]$ poderia ter ocorrido em $\tau{j}$.

### Processo de estimação iterativo de Turnbull

1.  Assumindo valores iniciais para $S(\tau_{j}), \; j = 0,...,m$;

2.  Calcular a probalidade de um evento ocorrer no tempo $\tau_{j}$ por:

$$p_{j} = S(\tau_{j-1}) - S(\tau_{j}), \;  j = 1,...,m.$$

3.  Estimar o número de eventos ocorridos em $\tau_{j}$ por:

$$d_{j}= \sum_{i=1}^{n} \frac{\alpha_{ij}p_{j}}{\sum_{k=1}^{m} \alpha_{ij}p_{j}}, \;  j = 1,..., m.$$

4.  Obter o número estimado de indivíduos sob risco $\tau_{j}$ por:

$$n_{j} = \sum_{k=1}^{m} d_{k}$$

4.  Atualizar o estimador produto-limite utilizando os resultados obtidos em 3 e 4.

#### Estimador Kaplan-Meier (produto-limite)

::: {#eq-Estimador-Kaplan-Meier}
$$\hat{S}(t) = \prod_{t_j \le t} \left( \frac{n_j - d_j}{n_j} \right) = \prod_{t_j \le t} \left( 1 - \frac{d_j}{n_j} \right)$$

**Onde:**

$d_j$: total de falhas em cada intervalo.

$n_j$: total de indivíduos sob risco.
:::

Se a estimativa atualizada de $S(\tau_{j})$ estiver próxima da anterior para todo $\tau_{j}$, encerre o processo iterativo, caso contrário, repetir os passos 2 a 4 utilizando as estimativas atualizadas de $S(\tau_{j})$.

O autor enfatiza que não ter algoritmo disponível em geral nos software estatísticos, sendo implementado no R pelos autores, utilizando estimador de Kaplan-Meier, em que os valores de $\tau_{j}$ assumi os tempos observados de falha.

## Modelos paramétricos

Em contexto de sobrevivência intervalar e sob o método de estimação visto, a natureza dos intervalos dados precisa considerar a construção da função de verossimilhança.

| Indivíduo               | T                    | Contribuição                  |
|-----------------------|---------------------|-----------------------------|
| Com tempo exto de falha | $$T = t$$            | $$f(t)$$                      |
| Censurado à direita     | $$T \in (L,\infty)$$ | $$S(l) - S(\infty) = S(l) $$  |
| Censura à esquerda      | $$T \in (0,U]$$      | $$S(0) - S(u) = 1 - S(u)$$    |
| Com tempo intervalar    | $$T \in (L,U]$$      | $$F(u) - S(l) = S(l) - S(u)$$ |

: Nota: T = tempo até a ocorrência do evento de interesse.

A função de verossimilhança $L(\theta)$ para $T_{i} \in (L_{i}, U_{i}] \; ou \; T_{i} \in (L_{i}, \infty)$, fica expresso por:

$$L(\theta) = \prod_{i=1}^{n} [S(l_{i} | x_{i}) - S(u_{i} | x_{i})]^{\delta_{i}}[S(l_{i} | x_{i})]^{(1-\delta_{i})}$$

**Onde:**

$x_{i}$: é o vetor de covariáveis associado ao i-ésimo paciente;

$\delta_{i} = 1$: se o evento ocorreu em ($L_{i},U_{i}$) e 0 se não ocorreu até $L_{I}$.

Após especificar o modelo paramétrico a função $L(\theta)$ fica determinada.
Posteriormente, os estimadores de máxima verossimilhança são obtidos, com as estatísticas assintóticas ( Wald e razão de verossimilhaças) possibilitando a realização de inferências sobre $\theta$.

## Resíduos para os modelos paramétricos

Para a avaliação de adequequação de modelos paramétricos para análise de dados, os resíduos continuam sendo fundamentais para verificação das suposições de modelos paramétricos tendo no caso a presença de censura intervalar.
Farrington \* apresenta alguns tipos de resíduos utilizados para verificar a adequação do modelo ajustado e a forma funcional de covariáveis contínuas.

> O livro diz que não software estatístico que implemente esses resíduos, não sendo fácil implementar na prática.

Como os resíduos de Cox-Snell podem ser obtidos pela implementação de um código simples de softwar R, são então eles, abordados.

## Resíduos de Cox-Snell

### Ausência de censura intervalar

Na ausência de censura intervalar os resíduos são baseados em uma v.a.
*T* com função de sobrevivência *S(t),* a v.a.
*-log\[S(T)\]* segue uma distribuição exponencial com média 1.
Para uma amostra de observações com censura intervalar ($l_1$,$u_1$,...,($l_n$,$u_n$\], em que $u_i =\infty$ para censura à direita, e função de sobrevivência estimada $\hat{S}_{i}(.)$, segue que o conjunto de intervalos, corresponde uma amostra de observações com censura intervalar, que devem seguir aproximadamente uma distribuição exponencial com média 1 para que o modelo seja considerado adequado.

O processo para verificar a adequação do modelo paramétrico ajustado, segue os seguintes passos:

1.  Ajuste de um modelo paramétrico aos dados, obtendo os resíduos de Cox-Snell;
2.  Para os resíduos de Cox-Snell (isto é, os *n* intervalor obtidos no passo 1), utilizar o estimado não paramétrico de Turnbull para obter as estimativas.
3.  Construir o gráfico dos conjuntos de intervalos *versus* a sequência de tempos que inclui os limites $L_i$ e $U_i$ que deve seguir uma exponencial padrão, isto é, passar pela origem e apresentar inclinação 1, para o modelo ajustado seja considerado adequado.
